repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]
      - id: detect-private-key
      - id: end-of-file-fixer

  # - repo: https://github.com/psf/black
  #   rev: 21.12b0
  #   hooks:
  #     - id: black

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_providers_lock
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_fmt
      - id: terraform_docs
      - id: checkov
      - id: terrascan
        args: [--args=--non-recursive] # avoids scan errors on subdirectories without Terraform config files

  - repo: https://github.com/pecigonzalo/pre-commit-terraform-vars
    rev: v1.0.0
    hooks:
      - id: terraform-vars

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.1.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]
