on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tflint:
    runs-on: ubuntu-latest

    name: Run Terraform Linter
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Cache plugin dir
        uses: actions/cache@v2
        with:
          path: ~/.tflint.d/plugins
          key: cache-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact
